# Generated by Django 4.2.6 on 2023-11-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('articulo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogApp.articulo')),
                ('interviewed_person', models.CharField(help_text='Nombre del entrevistado', max_length=200)),
                ('interviewed_person_position', models.CharField(help_text='Cargo del entrevistado', max_length=200)),
                ('interview_date', models.DateField(help_text='Fecha de la entrevista')),
                ('interviewer', models.CharField(help_text='Nombre del entrevistador', max_length=200)),
            ],
            bases=('blogApp.articulo',),
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('articulo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogApp.articulo')),
                ('topic', models.CharField(help_text='Tema de la guía', max_length=200)),
                ('duration', models.PositiveIntegerField(help_text='Duración estimada de la guía (en minutos)')),
            ],
            bases=('blogApp.articulo',),
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('articulo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogApp.articulo')),
                ('source', models.CharField(help_text='Fuente de la noticia', max_length=200)),
                ('publication_date', models.DateField(help_text='Fecha de publicación de la noticia')),
            ],
            bases=('blogApp.articulo',),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('articulo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogApp.articulo')),
                ('score', models.DecimalField(decimal_places=2, help_text='Puntuación de la reseña', max_digits=3)),
                ('review_date', models.DateField(help_text='Fecha de la reseña')),
            ],
            bases=('blogApp.articulo',),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('articulo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogApp.articulo')),
                ('category', models.CharField(help_text='Categoría del tutorial', max_length=200)),
                ('level', models.CharField(help_text='Nivel del tutorial (principiante, intermedio, avanzado)', max_length=50)),
            ],
            bases=('blogApp.articulo',),
        ),
    ]
